$(document).ready(function(){
    $("#showImage").click(function(){
      $('#imageHide').css("display","block");
        });
      $("#againHide").click(function(){
          $("#imageHide").css("display","none");
      });
      $('.showBtn').click(function(){
        $('.divWillHide').hide();
        $('.hidenModal').show();
      });
  });